### ISSUE TITLE
Missing the "refer" button on the profile page of a connection

### ISSUE THREAD

**Issue by terencesflam** [forbole/referral-network#11]
![screenshot 2019-01-24 at 11 03 15 am](https://user-images.githubusercontent.com/34306139/51651702-ec01ba80-1fc7-11e9-8b2c-e08693f258a0.png)

When I am viewing a profile of one of my connections, the "refer" button is missing.

**Comment by kwunyeung** [comment]
added at https://github.com/forbole/referral-network/commit/402257a971954e5b0b6da8207d9e50efd84529d0
